/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GameScore = IDL.Record({
  'highScore' : IDL.Nat,
  'gameName' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllGameScores' : IDL.Func([], [IDL.Vec(GameScore)], ['query']),
  'getGameScore' : IDL.Func([IDL.Text], [IDL.Opt(GameScore)], ['query']),
  'getTotalStars' : IDL.Func([], [IDL.Nat], ['query']),
  'saveGameScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateTotalStars' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GameScore = IDL.Record({
    'highScore' : IDL.Nat,
    'gameName' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllGameScores' : IDL.Func([], [IDL.Vec(GameScore)], ['query']),
    'getGameScore' : IDL.Func([IDL.Text], [IDL.Opt(GameScore)], ['query']),
    'getTotalStars' : IDL.Func([], [IDL.Nat], ['query']),
    'saveGameScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateTotalStars' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };